= Documentation utilisateur - DailyBank - Version 0
=
:toc-title: Sommaire
:toc: auto

*Date :* 07/05/2024 +
*Par :* Équipe 2A3 : _AMERI Mohammed, CIARDI Rudy, RAZAFINIRINA Mialisoa, SHULHINA Daria_

== I. Présentation générale
Bienvenue dans le guide utilisateur de l’application à destination des employés de DailyBank.

Ce guide vous servira à connaître dans les détails les différentes fonctions de l’application.

== II. Rôle de l' application
L'application DailyBank permettra de gérer les comptes bancaires de dépôt des clients. Elle permettra de réaliser les opérations suivantes :

* Consulter le solde d'un compte
* Effectuer des virements entre deux comptes
* Déposer ou retirer de l'argent sur un compte
* Suivre l'historique des transactions

L'application permettra également aux clients de gérer leurs profils et de contacter le service client.

== III. Installation utilisation
L'applicationsera installée sur les ordinateurs des guichetiers et des chefs d'agence de DailyBank. Une fois l'application installée, les clients pourront se connecter en utilisant leur login et leur mot de passe.

== IV. Fonctionnement - chaque étudiant identifie sa partie
L'application DailyBank se compose de plusieurs modules. Dans la version existante, un guichetier peut :

* Modifier informations client (adresse, téléphone, …)
* Créer un nouveau client
* Consulter un compte
* Débiter un compte (BD)

Un chef d’agence peut :

* Rendre inactif un client

Chaque module est responsable d'une fonctionnalité spécifique de l'application. Les modules communiquent entre eux pour fournir une expérience utilisateur fluide.

== V. Résultats produits avec jeux d'essai commentés
*Consulter le solde d'un compte* : nous vérifions que le client peut consulter le solde de son compte.

Le client se connecte à l'application puis sélectionne le compte qu'il souhaite consulter. L'écran devrait afficher le solde correct du compte.

*Effectuer des virements entre deux comptes* : nous vérifions que le client peut effectuer des virements entre ses deux comptes.

Le client est autorisé dans l'application, puis sélectionne le compte et le compte du destinataire pour le virement. Saisissez le montant du transfert et confirmez le transfert. Le virement doit être effectué correctement et le solde des deux comptes doit être mis à jour.

*Déposer de l'argent sur un compte* : nous vérifions que le client peut déposer de l'argent sur son compte.

Le client entre dans le programme et sélectionne le compte sur lequel il souhaite déposer de l'argent. Saisit le montant du dépôt et confirme le dépôt. Le dépôt doit être correct et le solde du compte à jour.

*Retirer de l'argent sur un compte* : nous vérifions si le client peut retirer de l'argent de son compte.

Le client entre dans le programme et sélectionne le compte sur lequel il souhaite retirer de l'argent. Saisissez le montant du retrait et confirmez le retrait. Le retrait s'est effectué correctement et le solde du compte a été mis à jour.

*Suivre l'historique des transactions* : nous vérifions que le client peut consulter l'historique des transactions dans son compte :

Le client entre dans le programme, puis sélectionne le compte pour lequel il souhaite consulter l'historique des transactions. L'historique des transactions doit être affiché à l'écran.
