= Document Technique - DailyBankApp
:toc-title: Sommaire
:toc: macro

*Version :* 0 +
*Date :* 07/05/2024 +
*Créé par :* Équipe 2A3 : _AMERI Mohammed, CIARDI Rudy, RAZAFINIRINA Mialisoa, SHULHINA Daria_ +
*Créé pour :* DailyBank +
*Projet :* SAE DEV/GPO (S2.01/S2.05)

'''

toc::[]

'''

== I Présentation de l'application (Mialy)
Dans le cadre de ce SAE 2.01, notre objectif est de développer une application qui permettra au banque de détail à s'orienter vers une expérience utilisateur "digitale". Cette application vise à améliorer et à moderniser plusieurs outils obsolètes et les processus bancaires existants afin d'effectuer correctement tout type d'action en restant sur une stratégie de réseaux physique et en s'assurant de l'efficacité et surtout de la sécurité. 

=== Fonctionnalités principales : 
Pour permettre le bon fonctionnement de l'application, elle devra permettre au guichetier au chef d'agence de réaliser des actions tel que : 

* Créer un nouveau compte
* Effectuer des débits 
* Effectuer des accréditations par virement de compte à compte ou par une personne physique
* Consulter et mettre à jour les informations sur les comptes (adresse, téléphone,...)
* Clôturer un compte

En plus de ces actions, l'application Daily Bank devra fournir au chef d'agence la possibilité de gérer des comptes, effectuer un débit exceptionnel et simuler un emprunt et une assurance d'emprunt.

=== Fonctionnalités supplémentaires : 
Sachant que l'application est une application dédiée au banque de détail, elle devra générer un relevé mensuel d'un compte en PDF et gérer des prélèvements automatiques.  

== II Architecture (Rudy)

== III Présentation Et Explication Des Diagrammes
=== 1 Use Case
=== 2 Diagramme De Classes (Mialy)


* AgenceBancaire : représente une agence et détient des attributs tels que : le nom de l'agence, son adresse (localisation), un chef d'agence et une liste d'employés travaillant dans cette agence.
* Employé : il s'agit d'une classe représentant les employés d'une banque. Ces employés peuvent être soit des guichetiers, soit un chef d'Agence.
* Client : est une classe qui contient toutes les informations relatives à un client de la banque. 
* Compte : représente un compte détenu par un client de la banque.

== IV Élément De Codes Significatifs Commentés 
